error: NERR_* to errno conversion function
The conversion is lossy, so it should be used only when necessary.

Signed-off-by: Josef 'Jeff' Sipek <jeffpc@josefsipek.net>